import { normalizeGmailMessage } from '../../src/providers/gmail/messages';
import { runInitialSync } from '../../src/sync';
import { buildLiveApp, type LiveApp, type SignedInUser } from './support/app';
import { b64url, gmailMessage } from './support/fake-gmail';
import { db, liveContext, messageIds, rawMessage } from './support/live';

/**
 * Message normalisation end to end: Gmail's native shape → normalizeGmailMessage →
 * SupabaseMessageStore → the live `messages` row (CONTRACT.md §4).
 */

const ctx = liveContext('norm');
let app: LiveApp;
let user: SignedInUser;

beforeAll(async () => {
  app = buildLiveApp(ctx);
  user = await app.signIn(1);
});
afterAll(async () => {
  jest.restoreAllMocks();
  await ctx.cleanup();
});

async function store(message: ReturnType<typeof gmailMessage>) {
  await app.messages.upsertMessages(user.userId, [normalizeGmailMessage(message)], new Date());
  const row = await rawMessage(user.userId, message.id ?? '');
  if (!row) throw new Error('row not stored');
  return row;
}

describe('base64url body decoding', () => {
  it('stores decoded text and HTML bodies, including URL-safe characters and UTF-8', async () => {
    const text = 'Ünïcödé ✓ ??>> ~~~';
    const html = '<p>Hëllo ??>></p>';
    expect(b64url(text) + b64url(html)).toMatch(/[-_]/);

    const row = await store(gmailMessage({ id: 'b64', text, html }, '1'));
    expect(row.body_text).toBe(text);
    expect(row.body_html).toBe(html);
  });

  it('falls back to payload.body.data for a single-part message', async () => {
    const message = gmailMessage({ id: 'single' }, '1');
    message.payload = {
      mimeType: 'text/plain',
      headers: message.payload?.headers,
      body: { data: b64url('single-part body') },
    };
    const row = await store(message);
    expect(row.body_text).toBe('single-part body');
    expect(row.body_html).toBeNull();
  });

  it('finds bodies nested in multipart/mixed and never stores an attachment', async () => {
    const message = gmailMessage({ id: 'nested' }, '1');
    message.payload = {
      mimeType: 'multipart/mixed',
      headers: message.payload?.headers,
      parts: [
        {
          mimeType: 'multipart/alternative',
          parts: [
            { mimeType: 'text/plain', body: { data: b64url('nested plain') } },
            { mimeType: 'text/html', body: { data: b64url('<b>nested</b>') } },
          ],
        },
        { mimeType: 'text/plain', filename: 'a.txt', body: { attachmentId: 'att-1' } },
      ],
    };
    const row = await store(message);
    expect(row.body_text).toBe('nested plain');
    expect(row.body_html).toBe('<b>nested</b>');
  });
});

describe('header extraction by name', () => {
  it.each(['lower', 'upper'] as const)('matches %s-case header names', async (headerCase) => {
    const row = await store(
      gmailMessage({ id: `hdr-${headerCase}`, subject: 'Case test', from: 'x@example.com', to: 'y@example.com', cc: 'z@example.com', headerCase }, '1'),
    );
    expect(row).toMatchObject({ subject: 'Case test', from_address: 'x@example.com', to_address: 'y@example.com', cc: 'z@example.com' });
  });

  it('stores empty strings for missing Subject/From/To and null for a missing Cc', async () => {
    const message = gmailMessage({ id: 'noheaders' }, '1');
    message.payload = { ...message.payload, headers: [] };
    expect(await store(message)).toMatchObject({ subject: '', from_address: '', to_address: '', cc: null });
  });
});

describe('from_address and to_address mapping', () => {
  it('maps From to from_address and To to to_address, verbatim', async () => {
    const row = await store(
      gmailMessage({ id: 'addr', from: '"Doe, Jane" <jane@example.com>', to: 'a@example.com, B <b@example.com>' }, '1'),
    );
    expect(row.from_address).toBe('"Doe, Jane" <jane@example.com>');
    expect(row.to_address).toBe('a@example.com, B <b@example.com>');
    expect(row).not.toHaveProperty('from');
    expect(row).not.toHaveProperty('to');
  });
});

describe('boolean derivation from labelIds', () => {
  it('is_read is generated by the database from label_ids', async () => {
    const unread = await store(gmailMessage({ id: 'unread', labels: ['INBOX', 'UNREAD'] }, '1'));
    const read = await store(gmailMessage({ id: 'read', labels: ['INBOX'] }, '1'));
    expect(unread.is_read).toBe(false);
    expect(read.is_read).toBe(true);
  });

  it('is_read follows label changes', async () => {
    await store(gmailMessage({ id: 'flip', labels: ['INBOX', 'UNREAD'] }, '1'));
    await app.messages.setMessageLabels(user.userId, 'flip', ['INBOX']);
    expect((await rawMessage(user.userId, 'flip'))?.is_read).toBe(true);
  });

  it('starred state is derivable from label_ids (no column)', async () => {
    const row = await store(gmailMessage({ id: 'star', labels: ['INBOX', 'STARRED'] }, '1'));
    expect(row.label_ids).toContain('STARRED');
    expect(row).not.toHaveProperty('is_starred');
  });
});

describe('other contract fields', () => {
  it('stores internalDate as received_at and historyId exactly, beyond 2^53', async () => {
    const row = await store(gmailMessage({ id: 'big', receivedAt: '2026-05-06T07:08:09.123Z' }, '9007199254740993'));
    expect(new Date(String(row.received_at)).toISOString()).toBe('2026-05-06T07:08:09.123Z');
    expect(row.history_text).toBe('9007199254740993');
  });

  it('re-syncing a message is an idempotent upsert on (user_id, id)', async () => {
    await store(gmailMessage({ id: 'twice', subject: 'first' }, '1'));
    await store(gmailMessage({ id: 'twice', subject: 'second' }, '2'));
    const { count } = await db.from('messages').select('id', { count: 'exact', head: true }).eq('user_id', user.userId).eq('id', 'twice');
    expect(count).toBe(1);
    expect((await rawMessage(user.userId, 'twice'))?.subject).toBe('second');
  });
});

describe('initial sync into Supabase', () => {
  it('stores exactly 50 of a larger inbox, newest first, skipping non-inbox mail', async () => {
    const other = await app.signIn(2);
    const gmail = app.gmail(other.googleId);
    for (let i = 0; i < 60; i += 1) {
      gmail.seed({ id: `m${String(i).padStart(2, '0')}`, receivedAt: new Date(Date.UTC(2026, 0, 1, 0, i)).toISOString() });
    }
    gmail.seed({ id: 'sent-only', labels: ['SENT'], receivedAt: '2027-01-01T00:00:00Z' });

    const { mailbox, settled } = await app.deps.connect(other.googleId);
    const result = await runInitialSync(other.userId, { mailbox, store: app.messages });
    await settled();

    expect(result).toEqual({ synced: 50 });
    const ids = await messageIds(other.userId);
    expect(ids).toHaveLength(50);
    expect(ids).not.toContain('sent-only');
    expect(ids).toContain('m59');
    expect(ids).not.toContain('m09'); // the ten oldest are beyond the first 50
  });
});
